"""
Module 07 - Lesson 01: Generator-Critic Reflection Agent Pattern
=====================================================================
Demonstrates building an iterative reflection loop between a Generator agent node
and a Critic agent node for self-correction and quality refinement.

Key Concepts Demonstrated:
---------------------------
1. Reflection Architecture: Separating output creation (Generator) from output
   evaluation (Critic) to improve generation quality.
2. Iterative Feedback Loops: Routing Critic feedback back to the Generator node
   to refine drafts based on concrete feedback.
3. Termination Guardrails: Using `should_continue` conditional edge to break out
   of reflection loops when quality criteria ('APPROVED') or max iteration bounds are met.
4. Stateful Loop Memory: Tracking iteration counts and draft versions inside `ReflectionState`.
"""

import os
import sys
import warnings
import logging
from typing import TypedDict

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

# ============================================================================
# SUPPRESS SDK / LOGGING VERBOSITY
# ============================================================================
class StderrFilter:
    def __init__(self, original_stderr):
        self.original_stderr = original_stderr

    def write(self, msg):
        if "automatic function calling" in msg or "AFC" in msg:
            return
        self.original_stderr.write(msg)

    def flush(self):
        if hasattr(self.original_stderr, "flush"):
            self.original_stderr.flush()

sys.stderr = StderrFilter(sys.stderr)

os.environ["PYTHONWARNINGS"] = "ignore"
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
warnings.showwarning = lambda *args, **kwargs: None

logging.getLogger("google").setLevel(logging.ERROR)
logging.getLogger("google.genai").setLevel(logging.ERROR)
logging.getLogger("langchain_google_genai").setLevel(logging.ERROR)

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, START, END

load_dotenv()

# ============================================================================
# STEP 1: DEFINE GRAPH STATE
# ============================================================================
# ReflectionState tracks the topic, active draft, critic feedback, and iteration count.
class ReflectionState(TypedDict):
    topic: str           # User topic prompt
    draft: str           # Latest output generated by Generator Agent
    critique: str        # Actionable evaluation from Critic Agent
    iteration: int       # Current loop count
    max_iterations: int  # Safety cap to prevent infinite loops

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.7)


# ============================================================================
# STEP 2: DEFINE GENERATOR & CRITIC NODES
# ============================================================================

def generator_node(state: ReflectionState) -> dict:
    """
    Agent A: Generator Node
    -----------------------
    On iteration 1, writes an initial draft overview.
    On subsequent iterations, rewrites the draft incorporating feedback from Critic Agent.
    """
    iteration = state.get("iteration", 0) + 1
    print(f"\n---> [Generator Agent] Draft Generation (Iteration {iteration})...")
    
    if iteration == 1:
        prompt = f"Write a short 3-sentence introductory overview on: {state['topic']}"
    else:
        prompt = (
            f"Revise the following draft based on the critic's feedback.\n"
            f"Current Draft: {state['draft']}\n"
            f"Critic Feedback: {state['critique']}"
        )
    res = llm.invoke(prompt).content.strip()
    return {"draft": res, "iteration": iteration}


def critic_node(state: ReflectionState) -> dict:
    """
    Agent B: Critic Node (Self-Correction Evaluator)
    ------------------------------------------------
    Evaluates the draft produced by Generator Node.
    Returns 2 actionable improvements or outputs 'APPROVED' if quality targets are met.
    """
    print(f"---> [Critic Agent] Reviewing Draft Quality...")
    prompt = (
        f"You are a strict editor. Review this draft on '{state['topic']}':\n{state['draft']}\n"
        f"Provide 2 actionable improvements for clarity and depth. If it is already high quality, type 'APPROVED'."
    )
    res = llm.invoke(prompt).content.strip()
    return {"critique": res}


# ============================================================================
# STEP 3: CONDITIONAL ROUTER (DECIDES WHETHER TO REVISE OR FINISH)
# ============================================================================
def should_continue(state: ReflectionState) -> str:
    """
    Conditional Routing Function:
    -----------------------------
    Inspects state.critique and state.iteration:
    - If 'APPROVED' is in critique OR iteration >= max_iterations -> returns 'end'
    - Otherwise -> returns 'generator' to trigger another revision pass
    """
    critique = state.get("critique", "")
    iteration = state.get("iteration", 0)
    max_iters = state.get("max_iterations", 2)
    
    if "APPROVED" in critique.upper() or iteration >= max_iters:
        print("   [Router Decision]: Draft approved or max iterations reached. Ending reflection loop.")
        return "end"
    else:
        print("   [Router Decision]: Improvements requested by Critic. Routing back to Generator.")
        return "generator"


# ============================================================================
# STEP 4: BUILD REFLECTION GRAPH ARCHITECTURE
# ============================================================================
builder = StateGraph(ReflectionState)

# Add Generator and Critic nodes
builder.add_node("generator", generator_node)
builder.add_node("critic", critic_node)

# Flow: START -> generator -> critic
builder.add_edge(START, "generator")
builder.add_edge("generator", "critic")

# Add conditional feedback loop edge from critic back to generator or END
builder.add_conditional_edges(
    "critic",
    should_continue,
    {
        "generator": "generator",
        "end": END
    }
)

app = builder.compile()


# ============================================================================
# STEP 5: EXECUTION DEMO
# ============================================================================
if __name__ == "__main__":
    print("=" * 65)
    print(" Module 07 - Lesson 01: Generator-Critic Reflection Loop ")
    print("=" * 65)

    res = app.invoke({
        "topic": "The Role of Micro-services in Distributed Systems",
        "max_iterations": 2
    })

    print("\n" + "=" * 65)
    print("--- FINAL REFINED DRAFT ---")
    print("=" * 65)
    print(res["draft"])
    print("=" * 65)
