"""
Module 05 - Lesson 01: Pydantic V2 State Schemas & Strict Validation
=====================================================================
Demonstrates using Pydantic V2 `BaseModel` schemas for strict type safety,
runtime validation, field default values, and rich metadata in LangGraph states.

Key Concepts Demonstrated:
---------------------------
1. Pydantic State Schema (`BaseModel`): Replaces standard `TypedDict` to enforce
   type constraints, automatic default initialization, and runtime field validation.
2. Field Descriptions & Metadata: Using `Field(description=..., default_factory=...)`
   to self-document graph state schemas.
3. Node State Interaction: Graph nodes receive and process validated Pydantic model instances
   or update state via dictionary keys matching Pydantic fields.
4. Auto-Validation on State Updates: LangGraph validates return dicts against the Pydantic schema
   at every step, raising explicit validation errors if types mismatch.
"""

import os
import sys
import warnings
import logging
from typing import List, Optional
from pydantic import BaseModel, Field

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

# ============================================================================
# SUPPRESS SDK / LOGGING VERBOSITY
# ============================================================================
class StderrFilter:
    def __init__(self, original_stderr):
        self.original_stderr = original_stderr

    def write(self, msg):
        if "automatic function calling" in msg or "AFC" in msg:
            return
        self.original_stderr.write(msg)

    def flush(self):
        if hasattr(self.original_stderr, "flush"):
            self.original_stderr.flush()

sys.stderr = StderrFilter(sys.stderr)

os.environ["PYTHONWARNINGS"] = "ignore"
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
warnings.showwarning = lambda *args, **kwargs: None

logging.getLogger("google").setLevel(logging.ERROR)
logging.getLogger("google.genai").setLevel(logging.ERROR)
logging.getLogger("langchain_google_genai").setLevel(logging.ERROR)

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.graph import StateGraph, START, END

load_dotenv()

# ============================================================================
# STEP 1: PYDANTIC V2 GRAPH STATE SCHEMA
# ============================================================================
# Passing a Pydantic BaseModel to StateGraph guarantees strict runtime type
# checking, field defaults, and error prevention. Unlike standard TypedDict,
# unhandled types or missing required fields trigger early validation errors.

class ResearchReportState(BaseModel):
    # Required string field with self-documenting Field metadata
    topic: str = Field(
        description="Target research topic to analyze"
    )
    
    # List fields with default_factory to prevent shared mutable default bugs
    query_list: List[str] = Field(
        default_factory=list,
        description="Search queries generated by the LLM"
    )
    
    raw_findings: List[str] = Field(
        default_factory=list,
        description="Collected research notes and facts"
    )
    
    # Optional field defaulting to None until populated by summarizer_node
    summary: Optional[str] = Field(
        default=None,
        description="Final executive summary synthesized from raw findings"
    )
    
    # Integer field initialized to 0
    word_count: int = Field(
        default=0,
        description="Calculated word count of the generated summary"
    )

# Initialize Gemini model for query generation and synthesis
llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.5)


# ============================================================================
# STEP 2: DEFINE GRAPH WORKFLOW NODES
# ============================================================================

def query_generator_node(state: ResearchReportState) -> dict:
    """
    Node 1: Generate Search Queries
    ------------------------------
    Takes state.topic and calls Gemini to break down the topic into 3 distinct
    search queries. Returns a list under the 'query_list' state key.
    """
    print("\n---> [Node 1: query_generator] Generating Search Queries with Gemini...")
    prompt = f"Generate 3 distinct search queries to research: '{state.topic}'. Output as a comma-separated list."
    res = llm.invoke(prompt).content
    
    # Split comma-separated string into a cleaned list of queries
    queries = [q.strip() for q in res.split(",") if q.strip()]
    
    # Returning dict keys matching Pydantic field names updates the model state
    return {"query_list": queries}


def researcher_node(state: ResearchReportState) -> dict:
    """
    Node 2: Gather Research Findings
    -------------------------------
    Simulates fetching research notes for each query stored in state.query_list.
    Returns a list of facts under the 'raw_findings' state key.
    """
    print("\n---> [Node 2: researcher] Collecting Research Data for Queries...")
    notes = []
    for query in state.query_list:
        notes.append(f"Fact regarding '{query}': Discovered key technological developments in 2025.")
        print(f"  + Researched: {query}")
    print(f"notes: {notes}")
    return {"raw_findings": notes}


def summarizer_node(state: ResearchReportState) -> dict:
    """
    Node 3: Synthesize Executive Summary
    -----------------------------------
    Combines state.raw_findings into a prompt for Gemini to produce a final report,
    calculates word count, and updates 'summary' and 'word_count' state fields.
    """
    print("\n---> [Node 3: summarizer] Synthesizing Findings into Executive Report...")
    combined_notes = "\n".join(state.raw_findings)
    prompt = f"Synthesize these research notes into a brief executive summary:\n{combined_notes}"
    res = llm.invoke(prompt).content.strip()
    
    return {
        "summary": res,
        "word_count": len(res.split())
    }


# ============================================================================
# STEP 3: BUILD AND COMPILE THE STATEGRAPH
# ============================================================================
# Pass the Pydantic class `ResearchReportState` directly to StateGraph
builder = StateGraph(ResearchReportState)

# Register node functions
builder.add_node("query_generator", query_generator_node)
builder.add_node("researcher", researcher_node)
builder.add_node("summarizer", summarizer_node)

# Define execution flow: START -> query_generator -> researcher -> summarizer -> END
builder.add_edge(START, "query_generator")
builder.add_edge("query_generator", "researcher")
builder.add_edge("researcher", "summarizer")
builder.add_edge("summarizer", END)

# Compile into executable LangGraph app
app = builder.compile()


# ============================================================================
# STEP 4: EXECUTION DEMO
# ============================================================================
if __name__ == "__main__":
    print("=" * 65)
    print(" Module 05 - Lesson 01: Pydantic V2 Validated Graph State ")
    print("=" * 65)

    # Initialize graph state using a Pydantic model instance
    initial_state = ResearchReportState(topic="Solid State Battery Technology")
    
    print(f"Initial State Topic: '{initial_state.topic}'")
    
    # Invoke workflow execution
    res = app.invoke(initial_state)

    # Output final validated Pydantic state results
    print("\n" + "=" * 65)
    print("--- Final Validated Pydantic State ---")
    print("=" * 65)
    print(f"Topic            : {res['topic']}")
    print(f"Generated Queries: {res['query_list']}")
    print(f"Word Count       : {res['word_count']}")
    print("-" * 65)
    print(f"Summary:\n{res['summary']}")
    print("=" * 65)
